---
aap_hostname: "aap.apps.hub.aws.tntinfra.net"
aap_validate_certs: false

dev_env_ssh_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;onboarding
          36366530383366633237356639303234343966326564663330353664386237393539316437323962
          3431313732333739396435663931363539613361613830390a363236366439316130653434643832
          30373833363438313361343465643363636233386639393964643439393361336332323830376435
          3037363133326136360a383635383533653531343562653630363933373630396437383763373565
          34663161633833663532613031663365383836336235396338393665323061383635333363623030
          37633933373261313535623166653232366165653437646639643463646535333031343538393738
          64343961643539643564346430393364613839316534653264386232353839656263303731363561
          35666664383836656137653965653762303331356134333936383761643864343035613364373161
          62386433306362353733383330393635326237343138656462616162393865313030343936363065
          62653935353630373362393132393439343839663935386565633035373561666539633030363031
          32343662616534656534396262636261613638613134343936303038303463643936636163316466
          65353537356563653130316439306663653464616264313834363137656236303665623135626538
          61626461336636663466323630306432356163326634323362383166316136306664626238623762
          33646132666531613862623330636663393564363330386665626465323663646634626634326331
          65376263636264633531663133653666323163656539333930346562393565383939346465656463
          65346136326237386437386236303361316665663765326161393433306531323864313363626165
          62656661303238303132643464306136613964643633633339326435633632393639646261343862
          66343362326464326366393033663933306534646539636439323931643639376538303232643165
          38383561363933656463383263333464656136613938356564383439346434656136326233303333
          34393266363333386136396632393663626536656362336331623964303337633839343264373238
          31333434386566373762373262623264383132653437306465303432626232303036613862373531
          37626639666336306366623862333430386662366236623034616135363765326237623261623330
          31663661376535336334313039386261376262653837363066623135346461323362386362323132
          33343931653830333432
