controller_credentials:
  - credential_type: Machine
    organization: "{{ tenant_name }}"
    name: "00-{{ tenant_name }}-dev-env-ssh-key"
    description: SSH private key for accessing development environment
    inputs:
      username: cloud-user
      ssh_key_data: "{{ dev_env_ssh_key }}"
