---
- name: Onboard new organizations
  hosts: "{{ aap_hostname | default('localhost') }}"
  connection: local
  run_once: true
  gather_facts: false
  vars:
    # aap_api_token get created during onboarding
    # it's a custom credential an
    aap_token: "{{ aap_api_token }}"

  roles:
    - infra.aap_configuration.dispatch
